### ISSUE TITLE
Write0 error

### ISSUE THREAD

**Issue by cyberponk** [NeiroNx/RTCLib#2] opened 2016-12-27 01:04 UTC
Getting error while compiling:

> RTClib.cpp: In member function uint8_t DS1302::begin()
> RTClib.cpp: 309:15: error: 'write0' was not declared in this scope
>    write0(0, sec)

Is `write0` a typo for `write`?

**Comment by NeiroNx** [comment] 2016-12-27 14:13
yes https://github.com/NeiroNx/RTCLib/commit/afb30d6a28fb4c4ad1d097f07a247e4ed16018c4

**Comment by zoomx** [comment] 2017-01-12 10:42
Maybe something went wrong since I downloaded this library today using the Library Manager on IDE 1.8.1 and got this error that was fixed on 5 Nov 2016.
I believe that Library Manager get files from this repository so I don't know why I get the older file.

**Comment by per1234** [comment] 2017-01-12 10:52
The problem is @NeiroNx forgot to update the value of `version` in library.properties before doing the 1.5.1 release so Library Manager never picked up version 1.5.1 of the library.

**Comment by zoomx** [comment] 2017-01-12 13:41
I downloaded this library for the first time. Maybe the downloading process take files from another place?

**Comment by NeiroNx** [comment] 2017-01-12 15:21
I am sorry just fogot update json and properties. Now publish a new release

**Closed** 2017-01-12 15:22 UTC
